# for bull/redis config: 
#    https://github.com/HugoDF/express-bull-es6
#    https://codewithhugo.com/setting-up-express-and-redis-with-docker-compose/
# for postgres config: https://codewithhugo.com/node-postgres-express-docker-compose/
# for compose file syntax: https://docs.docker.com/compose/compose-file/compose-file-v3/

# for production, change REACT_APP_SERVER_ROOT in ./client/.env.production file

version: "3"
services:
  redis:
    image: redis
    container_name: bull
    expose:
      - 6379

  database:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: albumview

  web:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    ports:
      - 8080:8080
    environment:
      - REDIS_URL=redis://bull
      - THE_AUDIO_DB_API_KEY=1
      - THE_AUDIO_DB_INTERVAL=500
    command:
      sh -c 'cd ./client && npm run build && cd .. && npm run migrate && node ./server/index.js'

  worker:
    build: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    depends_on:
      - database
      - redis
      - web
    links:
      - database
      - redis
    environment:
      - REDIS_URL=redis://bull
      - NODE_ENV=production
      - PORT=8080
      - THE_AUDIO_DB_API_KEY=1
      - THE_AUDIO_DB_INTERVAL=500
    command:
      sh -c 'node ./server/worker.js'
